project:
  type: book
  output-dir: report
book:
  title: "PopPK Report Title"
  chapters:
    - index.qmd # executive summary (first chapter needs to be named index and in root directory)
    - sections/2_introduction.qmd
    - sections/3_objectives.qmd
    - sections/4_data.qmd
    - sections/5_methods.qmd
    - sections/6_results.qmd
    - sections/7_discussion.qmd
    - sections/8_conclusion.qmd
    - sections/9_references.qmd
    - sections/10_appendices.qmd
    - sections/11_tips.qmd
format:
  pdf:
    documentclass: scrreprt
    toc: true
    template-partials:
      - engine/partials/title.tex
      - engine/partials/before-body.tex
      - engine/partials/toc.tex
    include-in-header:
      - engine/header.tex
    keep-tex: true
    toccolor: blue
    lof: true
    lot: true
    toc-title: "Table of Contents"
    link-citations: true
    number-sections: true
    start-numbering: 1
    colorlinks: true
    classoption:
      - toc=chapterentrywithdots
      - 11pt
      - headings=small
    crossref:
      lof-title: List of Figures
      lot-title: List of Tables
    hyperrefoptions:
    - linktoc=all
    - pdfpagemode=FullScreen
    - bookmarks=true
    geometry:
      - margin=.75in
      - left=1in
      - right=1in
      - top=1in
      - bottom=3cm
      - footskip=2cm
      - marginparwidth=1in
      - marginparsep=0.75cm
    mainfont: Times New Roman
    sansfont: Times New Roman
    mainfontoptions:
        - Path=./engine/misc/Times/
        - Extension=.ttf
        - UprightFont=*
        - BoldFont=* Bold
        - ItalicFont=* Italic
    sansfontoptions:
        - Path=./engine/misc/Times/
        - Extension=.ttf
        - UprightFont=*
        - BoldFont=* Bold
        - ItalicFont=* Italic



# Define Metadata For Cover Page
bibliography: engine/ref.bib
report-number: "PopPK-001"
report-title: "PopPK Report Title"
drug-name: "Drug A"
indication: "Disease X"
study-number: ABC-12345
sponsor: ISoP Standards and Best Practices Working Group
author: PB, MMJ, AR
review: PB, MMJ, AR
approve: PB, MMJ, AR
date: today
date-format: "DD MMM YYYY"
status: DRAFT
copyright:
  text: "This is a Company Name. document that contains confidential information. It is intended solely for the recipient and must not be disclosed to any other party. This material may be used only for evaluating or conducting clinical investigations; any other proposed use requires written consent from Company Name."
